valid_flavors: list[str] = [
    "Original",
    "Açaí Berry",
    "Arctic-Berry",
    "Beach Breeze",
    "Blueberry",
    "Cactus Fruit",
    "Cranberry",
    "Coconut Berry",
    "Dragon Fruit",
    "Fig Apple",
    "Grapefruit Twist",
    "Juneberry",
    "Kiwi-Apple",
    "Lime",
    "Limeade",
    "Ocean Blast",
    "Tangerine",
    "Peach-Nectarine",
    "Pear",
    "Pear Cinnamon",
    "Plum Twist",
    "Pomegranate",
    "Strawberry Apricot",
    "Tropical",
    "Watermelon",
]
